### ISSUE TITLE
Connect to real Cosmos DB account from local

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/Dash-Seedling#12]
Currently we're enforcing looking for a Cosmos key when running locally - we should have a flag in the env to use cosmos AAD creds to connect to a remote cosmos instance

**Comment by t-young31** [comment]
Agree – raised in #10 ([comment](https://github.com/UCLH-Foundry/Dash-Seedling/pull/10#discussion_r1172791387)) I think there should be a separate flow for connecting to a cloud cosmos/mssql/appinsights (that doesn't involve `make serve-local` – not that I have any good ideas on naming!)

> we should have a flag in the env to use cosmos AAD creds to connect to a remote cosmos instance

I'd rather not have a flag, but a different `.env.X.sample`. Or do we want to support any combination of service A cloud and service B locally hosted?
