### ISSUE TITLE
Install SQL ODBC driver in devcontainer

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/Dash-Seedling#13]
For convenience when connecting to a feature store locally, we should include the MSSQL ODBC driver devcontainer feature to install this, so that developers can query it without needing to do a manual install

**Comment by t-young31** [comment]
I strongly disagree that we should have similar (but almost certainly not quite the same) installs in a devcontainer when the [image that gets deployed](https://github.com/UCLH-Foundry/Dash-Seedling/blob/main/app/Dockerfile) has exactly the same requirements.

**Comment by lawrenceadams** [comment]
Does that mean that when developing the app locally we are expected to be running it within a container/`make serve-local` instead of `python app/app.py` @t-young31 ?

**Comment by t-young31** [comment]
https://github.com/UCLH-Foundry/Dash-Seedling/pull/17 contains my suggestion, where I'd vote you run `make serve-dev` (or whatever is decided naming wise). I guess you could also open it in a devcontainer (as per https://github.com/UCLH-Foundry/Dash-Seedling/pull/16) and run `python app/app.py`, but then need to set env vars manually 

(we'd just not got round to working out the workflow for developing against azure services!)
